### ISSUE TITLE
CLI performance

### ISSUE THREAD

**Issue by MaxVerevkin** [bim9262/calibright#13]
I've recently noticed that my brightness keybindings have some noticeable delay:

```
~ ❯ time calibright_cli --dec 5
calibright_cli --dec 5  0.02s user 0.02s system 8% cpu 0.402 total
```

0.4 seconds is pretty slow. I believe it wasn't the case before. Will investigate at some point.

**Comment by bim9262** [comment]
Are you using ddcci? I saw there was a new version (in AUR), but didn't do a performance test before and after.

**Comment by MaxVerevkin** [comment]
Yes, I do. Currently I have my external display unplugged, so I didn't even thought about that. I just reloaded the ddcci module and the delay disappeared. I wonder if something can be done on `calibright`s side...

**Comment by bim9262** [comment]
Hmm... I wonder if the hang it's repeatable. If you plug in you monitor, reload the module, then unplug does it hang again?

My guess is that this can be mitigated by setting the `ddcci_sleep_multiplier` and/or `ddcci_max_tries_write_read`

**Comment by MaxVerevkin** [comment]
I connected my display, reloaded the module, and the delay is now 0.2 seconds.

```toml
[global]
ddcci_sleep_multiplier = 0
ddcci_max_tries_write_read = 1
```

does not change anything (everything still works but the delay is there)

**Comment by bim9262** [comment]
Is this slow too?

`ls /sys/class/backlight/*`

**Comment by MaxVerevkin** [comment]
No. Even `cat /sys/class/backlight/ddcci3/brightness` is fast.

**Comment by bim9262** [comment]
If the device still exists in /sys then calibright will still try to set the brightness with dbus and then fall back to writing to the brightness file. My guess is that the dbus set is what's taking the most time.

I thought that the device was removed from /sys when it was unplugged, maybe I'm misremembering or maybe a different version of the module behaved differently.

**Comment by MaxVerevkin** [comment]
> I thought that the device was removed from /sys when it was unplugged

No :(

> My guess is that the dbus set is what's taking the most time.

Hm, maybe! I'll test this theory tomorrow.

**Comment by MaxVerevkin** [comment]
> I'll test this theory tomorrow.

It doesn't happen today :confused:

**Comment by bim9262** [comment]
It's annoying that it's inconsistent, but at the same time I'm glad that it's acting better now
